# Generated by Django 6.0 on 2025-12-16 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_rename_doctor_appointment_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Mobile',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='MedicalFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Medical Report', max_length=200)),
                ('file', models.FileField(upload_to='medical_files/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_files', to='hospital.patient')),
            ],
        ),
    ]
