# Generated by Django 6.0.3 on 2026-03-19 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_billingitem_remove_bill_amount_remove_bill_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='billingitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='billitem',
            name='discount',
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('paid', 'Paid')], default='unpaid', max_length=20),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(default='Receptionist', max_length=50)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
